### PR TITLE
Adds alembic dependency (Fixed missing , )

### PR DESCRIPTION
**Pull request by RUKip**
Adds alembic dependency and fixes typo. Part of issue: https://github.com/keylime/ansible-keylime/issues/19

### CODE REVIEW

**Review by mpeters — APPROVED** [review]
lgtm

**Comment by mpeters** [comment]
CI is currently failing because of a previous (unrelated commit). Opening separate issue to track: https://github.com/keylime/ansible-keylime/issues/21

**Comment by mpeters** [comment]
@RUKip would you mind rebasing your PR and then re-pushing? I've fixed the issues with the CI but in order for your PR to pick up the travis CI configuration it needs to be rebased.

**Comment by RUKip** [comment]
@mpeters Now passes!

**Pull request merged**
